// L2 · runtime — barrel. Object model mínimo (walking skeleton): representación
// de objeto, classOf, bootstrapKernel y SymbolTable. L3 (eval/send/primitivas)
// consume estos tipos e instala las primitivas en los methodDict.

export { bootstrapKernel, makeClassWithMetaclass } from "./kernel.js";
export {
  basicNew,
  classOf,
  type HandlerActionKind,
  HandlerActionSignal,
  type HandlerContext,
  type HomeMarker,
  identical,
  identityHash,
  instVarAt,
  instVarAtPut,
  isArray,
  isCharacter,
  isFloat,
  isInterval,
  lookupMethod,
  type Message,
  makeArray,
  makeCharacter,
  makeFloat,
  makeInterval,
  makeOrderedCollection,
  NonLocalReturn,
  notIdentical,
  ObjectFormat,
  type Primitive,
  type Scope,
  SignalException,
  type STArray,
  type STCharacter,
  type STClass,
  type STClosure,
  type STFloat,
  type STInterval,
  type STObject,
  type STOrderedCollection,
  type STValue,
  type Universe,
  Unwind,
} from "./object.js";
export { type STSymbol, type SymbolId, SymbolTable } from "./symbol-table.js";
